name: Android CI Build

on:
  push:
    branches: [ "main" ] # Adjust if your main branch is master
  pull_request:
    branches: [ "main" ] # Adjust if your main branch is master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2 # This action handles SDK, NDK, CMake
      # with:
        # ndk-version: '25.2.9519653' # Optional: specify NDK version if needed
        # cmake-version: '3.22.1' # Optional: specify CMake version if needed

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease
      # Or use assembleDebug if release signing is not set up:
      # run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
        # If building debug, change path:
        # path: app/build/outputs/apk/debug/app-debug.apk
