name: Android CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: List APK output files
      run: |
        echo "Listing app/build/outputs/apk/release:"
        ls -R app/build/outputs/apk/release || echo "app/build/outputs/apk/release not found or empty"
        echo "----"
        echo "Listing app/build/outputs/apk:"
        ls -R app/build/outputs/apk || echo "app/build/outputs/apk not found or empty"
        echo "----"
        echo "Listing app/build/outputs:"
        ls -R app/build/outputs || echo "app/build/outputs not found or empty"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-unsigned
        path: app/build/outputs/apk/release/app-release-unsigned.apk
